import { Scheme, LeaderboardUser, RedeemPerk } from './types';
import { StoreIcon } from './components/icons/StoreIcon';
import { ScholarshipIcon } from './components/icons/ScholarshipIcon';

export const RECOMMENDED_SCHEMES: Scheme[] = [
  {
    id: '1',
    title: 'National Scholarship for Students',
    department: 'Ministry of Education',
    description: 'Scholarship for meritorious students across India.',
    eligibility: 'Students scoring above 80% in Class 12',
    link: 'https://scholarships.gov.in',
    category: 'Student',
    tags: ['student', 'urgent'],
  },
  {
    id: '2',
    title: 'PM Kisan Scheme',
    department: 'Ministry of Agriculture',
    description: 'Direct income support for farmers.',
    eligibility: 'Small and marginal farmers',
    link: 'https://pmkisan.gov.in',
    category: 'Farmer',
    tags: ['farmer'],
  },
  {
    id: '3',
    title: 'Mahila Samman Yojana',
    department: 'Women & Child Development',
    description: 'Support scheme for women entrepreneurs.',
    eligibility: 'Women aged 18-40 with a business idea',
    link: 'https://wcd.nic.in',
    category: 'Women',
    tags: ['women'],
  },

  // === All 30 Scholarships Added Below ===

  {
    id: '4',
    title: 'Central Sector Scholarship',
    department: 'Department of Higher Education',
    description: '₹10,000 - ₹20,000 per annum for meritorious college students.',
    eligibility: 'Family income < ₹8L, age 17-22',
    link: 'https://scholarships.gov.in/',
    category: 'Scholarship',
    tags: ['college', 'merit'],
  },
  {
    id: '5',
    title: 'AICTE Pragati Scholarship for Girls',
    department: 'AICTE',
    description: '₹50,000 per annum for girl students in technical courses.',
    eligibility: 'Girls enrolled in B.Tech/B.E., income < ₹8L',
    link: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
    category: 'Scholarship',
    tags: ['girls', 'engineering'],
  },
  {
    id: '6',
    title: 'PM YASASVI Scheme',
    department: 'Ministry of Social Justice & Empowerment',
    description: 'Up to ₹1.25 lakh for OBC, EBC, and DNT students.',
    eligibility: 'OBC/EBC/DNT, income < ₹2.5L',
    link: 'https://yet.nta.ac.in/',
    category: 'Scholarship',
    tags: ['obc', 'minority'],
  },
  {
    id: '7',
    title: 'UP Post Matric Scholarship',
    department: 'Government of Uttar Pradesh',
    description: 'Financial aid for UP students in higher education.',
    eligibility: 'Residents of UP, income < ₹2L',
    link: 'https://scholarship.up.gov.in/',
    category: 'Scholarship',
    tags: ['state', 'up'],
  },
  {
    id: '8',
    title: 'NTSE Scholarship',
    department: 'NCERT',
    description: '₹1,250 - ₹2,000 per month for Class 10 students.',
    eligibility: 'Class 10 students qualifying NTSE exam',
    link: 'https://ncert.nic.in',
    category: 'Scholarship',
    tags: ['school', 'merit'],
  },
  {
    id: '9',
    title: 'INSPIRE Scholarship',
    department: 'DST',
    description: '₹80,000 per annum for science students.',
    eligibility: 'B.Sc./M.Sc. students, income < ₹8L',
    link: 'https://online-inspire.gov.in/',
    category: 'Scholarship',
    tags: ['science'],
  },
  {
    id: '10',
    title: 'KVPY Scholarship',
    department: 'DST',
    description: '₹5,000 - ₹7,000 per month for science streams.',
    eligibility: 'B.Sc./B.Stat students qualifying KVPY',
    link: 'http://kvpy.iisc.ernet.in/',
    category: 'Scholarship',
    tags: ['research'],
  },
  {
    id: '11',
    title: 'Saksham Scholarship',
    department: 'AICTE',
    description: '₹50,000 per year for differently-abled engineering students.',
    eligibility: 'Disability + B.Tech enrollment',
    link: 'https://aicte-india.org/schemes/students-development-schemes/Saksham',
    category: 'Scholarship',
    tags: ['disability'],
  },
  {
    id: '12',
    title: 'National Fellowship for OBC',
    department: 'UGC',
    description: '₹25,000 monthly fellowship for OBC students.',
    eligibility: 'OBC category postgraduates',
    link: 'https://ugc.ac.in',
    category: 'Scholarship',
    tags: ['obc'],
  },
  {
    id: '13',
    title: 'Maulana Azad Fellowship',
    department: 'Ministry of Minority Affairs',
    description: '₹28,000 per month for minority students.',
    eligibility: 'Muslim/Christian/Sikh/Buddhist/Parsi students',
    link: 'https://minorityaffairs.gov.in',
    category: 'Scholarship',
    tags: ['minority'],
  },
  {
    id: '14',
    title: 'Begum Hazrat Mahal Scholarship',
    department: 'MAEF',
    description: 'Up to ₹12,000 for female minority students.',
    eligibility: 'Female + minority category',
    link: 'https://maef.nic.in',
    category: 'Scholarship',
    tags: ['female'],
  },
  {
    id: '15',
    title: 'National Means-cum-Merit Scholarship',
    department: 'MHRD',
    description: '₹12,000 per year for Class 8 students.',
    eligibility: 'Income < ₹1.5L + Class 8',
    link: 'https://scholarships.gov.in',
    category: 'Scholarship',
    tags: ['school'],
  },
  {
    id: '16',
    title: 'ISHAN UDAY Scholarship',
    department: 'UGC',
    description: '₹5,400–₹7,800 monthly for NE students.',
    eligibility: 'Resident of North Eastern Region',
    link: 'https://ugc.ac.in',
    category: 'Scholarship',
    tags: ['northeast'],
  },
  {
    id: '17',
    title: 'PMRF',
    department: 'Ministry of Education',
    description: '₹70,000 monthly for PhD students.',
    eligibility: 'PhD in top institutes',
    link: 'https://pmrf.in',
    category: 'Scholarship',
    tags: ['phd'],
  },
  {
    id: '18',
    title: 'AIIMS Fellowship',
    department: 'AIIMS',
    description: '₹25,000 monthly for MD/MS students.',
    eligibility: 'Medical postgraduates',
    link: 'https://aiimsexams.ac.in',
    category: 'Scholarship',
    tags: ['medical'],
  },
  {
    id: '19',
    title: 'CSIR NET JRF',
    department: 'CSIR',
    description: '₹31,000/month fellowship for science postgrads.',
    eligibility: 'M.Sc. + NET qualified',
    link: 'https://csirnet.nta.ac.in',
    category: 'Scholarship',
    tags: ['jrf'],
  },
  {
    id: '20',
    title: 'UGC NET JRF',
    department: 'UGC',
    description: '₹31,000/month fellowship for postgrads.',
    eligibility: 'MA/M.Com/M.Sc. + NET',
    link: 'https://ugcnet.nta.nic.in',
    category: 'Scholarship',
    tags: ['ugc'],
  },
  {
    id: '21',
    title: 'LIC Golden Jubilee Scholarship',
    department: 'LIC',
    description: '₹10,000 annually for low-income families.',
    eligibility: 'Income < ₹2L',
    link: 'https://licindia.in',
    category: 'Scholarship',
    tags: ['lic'],
  },
  {
    id: '22',
    title: 'Siemens Scholarship',
    department: 'Siemens India',
    description: '₹75,000 per year for B.E./B.Tech students.',
    eligibility: 'Meritorious engineering students',
    link: 'https://www.siemens.co.in',
    category: 'Scholarship',
    tags: ['engineering'],
  },
  {
    id: '23',
    title: 'FFE India Scholarship',
    department: 'FFE',
    description: 'Tuition + living cost for needy students.',
    eligibility: 'B.Tech/MBBS students',
    link: 'https://ffe.org',
    category: 'Scholarship',
    tags: ['tech', 'mbbs'],
  },
  {
    id: '24',
    title: 'GATE Scholarship',
    department: 'MHRD',
    description: '₹12,400 per month for M.Tech students.',
    eligibility: 'Valid GATE score',
    link: 'https://education.gov.in',
    category: 'Scholarship',
    tags: ['gate'],
  },
  {
    id: '25',
    title: 'Nikon Scholarship',
    department: 'Nikon India',
    description: '₹1L for photography/design courses.',
    eligibility: 'Creative field students',
    link: 'https://buddy4study.com',
    category: 'Scholarship',
    tags: ['design'],
  },
  {
    id: '26',
    title: 'HDFC Parivartan ECS Scholarship',
    department: 'HDFC Bank',
    description: '₹15k to ₹75k for underprivileged students.',
    eligibility: 'Income < ₹3L',
    link: 'https://buddy4study.com',
    category: 'Scholarship',
    tags: ['hdfc'],
  },
  {
    id: '27',
    title: 'ONGC Scholarship for Meritorious Students',
    department: 'ONGC',
    description: '₹48,000 annually for selected courses.',
    eligibility: 'Engineering/MBBS/MBA/Geology',
    link: 'https://www.ongcscholar.org',
    category: 'Scholarship',
    tags: ['merit'],
  },
  {
    id: '28',
    title: 'Aditya Birla Scholarship',
    department: 'Aditya Birla Group',
    description: '₹1.8L per annum for MBA/Law students.',
    eligibility: 'Select institutes',
    link: 'https://www.adityabirlascholars.net',
    category: 'Scholarship',
    tags: ['mba', 'law'],
  },
  {
    id: '29',
    title: 'Sitaram Jindal Scholarship',
    department: 'SJF',
    description: '₹500–₹3,200 monthly for low-income students.',
    eligibility: 'Income < ₹4L',
    link: 'http://www.sitaramjindalfoundation.org',
    category: 'Scholarship',
    tags: ['jindal'],
  },
  {
    id: '30',
    title: 'Sashakt Scholarship',
    department: 'Dr. Reddy’s Foundation',
    description: '₹2.4L for 3 years for B.Sc. girls.',
    eligibility: 'B.Sc. + Female',
    link: 'https://www.sashaktscholarship.org',
    category: 'Scholarship',
    tags: ['female', 'science'],
  },
  {
    id: '31',
    title: 'ONGC SC/ST Scholarship',
    department: 'ONGC',
    description: '₹48,000 per annum for SC/ST students.',
    eligibility: 'SC/ST category',
    link: 'https://www.ongcscholar.org',
    category: 'Scholarship',
    tags: ['sc', 'st'],
  },
  {
    id: '32',
    title: 'Tata Trusts Scholarship',
    department: 'Tata Trusts',
    description: 'Scholarships for various courses.',
    eligibility: 'As per course',
    link: 'https://www.tatatrusts.org',
    category: 'Scholarship',
    tags: ['trust'],
  },
  {
    id: '33',
    title: 'Fair and Lovely Foundation Scholarship',
    department: 'Fair and Lovely Foundation',
    description: '₹25k–₹1L for girls from low-income families.',
    eligibility: 'Female, income < ₹3L',
    link: 'https://www.fairandlovelyfoundation.in',
    category: 'Scholarship',
    tags: ['female'],
  },
];

export const LEADERBOARD_DATA: LeaderboardUser[] = [
  { rank: 1, name: 'Ramesh Kumar', location: 'Punjab', tokens: 250, avatarUrl: 'https://i.pravatar.cc/150?img=1' },
  { rank: 2, name: 'Sunita Devi', location: 'Uttar Pradesh', tokens: 235, avatarUrl: 'https://i.pravatar.cc/150?img=5' },
  { rank: 3, name: 'Arjun Singh', location: 'Rajasthan', tokens: 210, avatarUrl: 'https://i.pravatar.cc/150?img=3' },
  { rank: 4, name: 'Priya Sharma', location: 'Maharashtra', tokens: 198, avatarUrl: 'https://i.pravatar.cc/150?img=8' },
  { rank: 5, name: 'Amit Patel', location: 'Gujarat', tokens: 180, avatarUrl: 'https://i.pravatar.cc/150?img=7' },
  { rank: 6, name: 'Kavita Reddy', location: 'Andhra Pradesh', tokens: 172, avatarUrl: 'https://i.pravatar.cc/150?img=11' },
  { rank: 7, name: 'Sandeep Tiwari', location: 'Madhya Pradesh', tokens: 165, avatarUrl: 'https://i.pravatar.cc/150?img=12' },
  { rank: 8, name: 'Anjali Das', location: 'West Bengal', tokens: 150, avatarUrl: 'https://i.pravatar.cc/150?img=14' },
];

export const REDEEM_PERKS: RedeemPerk[] = [
  {
    id: 'resume-review',
    name: 'AI Resume Review',
    description: 'Get an expert-level review of your resume, highlighting strengths and areas for improvement.',
    price: 50,
    icon: ScholarshipIcon,
  },
  {
    id: 'study-pdf',
    name: 'Exclusive Study Materials PDF',
    description: 'Download a PDF with curated study notes for competitive exams.',
    price: 75,
    icon: StoreIcon,
  },
  {
    id: 'mock-interview',
    name: 'Mock Interview Session',
    description: 'A 30-minute one-on-one mock interview session with an AI career coach.',
    price: 150,
    icon: ScholarshipIcon,
  },
];