import { Scheme, LeaderboardUser, RedeemPerk } from './types';
import { StoreIcon } from './components/icons/StoreIcon';
import { ScholarshipIcon } from './components/icons/ScholarshipIcon';
import { Scholarship } from './types';

export const RECOMMENDED_SCHOLARSHIPS: Scholarship[] = [
  {
    id: '1',
    name: 'AICTE Pragati Scholarship for Girls',
    provider: 'AICTE',
    deadline: '31 August 2025',
    amount: '₹50,000/year',
    link: 'https://aicte-india.org/schemes/students-development-schemes',
    eligibility: {
      minAge: 17,
      maxAge: 25,
      course: ['B.Tech'],
      caste: ['SC', 'ST', 'OBC'],
      maxIncome: 800000,
      state: ['All'],
    },
  },
  {
    id: '2',
    name: 'Post Matric Scholarship for SC Students',
    provider: 'State Government (UP)',
    deadline: '15 September 2025',
    amount: '₹12,000/year',
    link: 'https://scholarship.up.gov.in',
    eligibility: {
      minAge: 16,
      maxAge: 28,
      course: ['B.A.', 'B.Com', 'B.Sc'],
      caste: ['SC'],
      maxIncome: 250000,
      state: ['Uttar Pradesh'],
    },
  },
  {
    id: '3',
    name: 'Merit-cum-Means Scholarship',
    provider: 'Ministry of Minority Affairs',
    deadline: '10 September 2025',
    amount: '₹20,000/year',
    link: 'https://scholarships.gov.in',
    eligibility: {
      minAge: 17,
      maxAge: 30,
      course: ['B.Tech', 'M.Tech'],
      caste: ['OBC', 'EWS'],
      maxIncome: 250000,
      state: ['All'],
    },
  },
  {
    id: '4',
    name: 'Saksham Scholarship for Differently Abled Students',
    provider: 'AICTE',
    deadline: '20 August 2025',
    amount: '₹50,000/year',
    link: 'https://aicte-india.org/schemes/students-development-schemes',
    eligibility: {
      minAge: 18,
      maxAge: 28,
      course: ['B.Tech', 'Diploma'],
      caste: ['All'],
      maxIncome: 800000,
      state: ['All'],
    },
  },
  {
    id: '5',
    name: 'State Merit Scholarship',
    provider: 'Kerala Government',
    deadline: '10 October 2025',
    amount: '₹10,000/year',
    link: 'https://dcescholarship.kerala.gov.in',
    eligibility: {
      minAge: 17,
      maxAge: 24,
      course: ['B.Sc', 'M.Sc'],
      caste: ['General', 'OBC'],
      maxIncome: 600000,
      state: ['Kerala'],
    },
  },
  {
    id: '6',
    name: 'Ishan Uday Scholarship for North Eastern Students',
    provider: 'UGC',
    deadline: '5 September 2025',
    amount: '₹7,800/month',
    link: 'https://scholarships.gov.in',
    eligibility: {
      minAge: 17,
      maxAge: 25,
      course: ['B.Tech', 'B.A.'],
      caste: ['All'],
      maxIncome: 450000,
      state: ['Assam', 'Meghalaya', 'Nagaland', 'Tripura'],
    },
  },
  {
    id: '7',
    name: 'EBC Post Matric Scholarship',
    provider: 'Bihar Government',
    deadline: '20 October 2025',
    amount: '₹10,000/year',
    link: 'https://pmsonline.bih.nic.in',
    eligibility: {
      minAge: 17,
      maxAge: 28,
      course: ['B.A.', 'B.Com', 'B.Sc'],
      caste: ['EBC'],
      maxIncome: 200000,
      state: ['Bihar'],
    },
  },
  {
    id: '8',
    name: 'National Means-cum-Merit Scholarship (NMMS)',
    provider: 'Ministry of Education',
    deadline: '30 September 2025',
    amount: '₹12,000/year',
    link: 'https://scholarships.gov.in',
    eligibility: {
      minAge: 13,
      maxAge: 16,
      course: ['8th', '9th', '10th'],
      caste: ['All'],
      maxIncome: 150000,
      state: ['All'],
    },
  },
  {
    id: '9',
    name: 'Jharkhand Post Matric Scholarship',
    provider: 'Jharkhand Welfare Department',
    deadline: '25 September 2025',
    amount: '₹10,000/year',
    link: 'https://ekalyan.cgg.gov.in',
    eligibility: {
      minAge: 17,
      maxAge: 28,
      course: ['B.Tech', 'M.Tech'],
      caste: ['ST', 'SC', 'OBC'],
      maxIncome: 250000,
      state: ['Jharkhand'],
    },
  },
  {
    id: '10',
    name: 'Prime Minister’s Scholarship for Wards of Police Personnel',
    provider: 'National Scholarship Portal',
    deadline: '1 October 2025',
    amount: '₹36,000/year',
    link: 'https://scholarships.gov.in',
    eligibility: {
      minAge: 17,
      maxAge: 25,
      course: ['B.Tech', 'MBBS', 'BDS'],
      caste: ['OBC', 'SC', 'ST'],
      maxIncome: 900000,
      state: ['All'],
    },
  },
  {
    id: '11',
    name: 'MOMA Scholarship for Minorities',
    provider: 'Ministry of Minority Affairs',
    deadline: '28 August 2025',
    amount: '₹25,000/year',
    link: 'https://scholarships.gov.in',
    eligibility: {
      minAge: 18,
      maxAge: 30,
      course: ['B.Tech', 'MCA'],
      caste: ['All'],
      maxIncome: 300000,
      state: ['All'],
    },
  },
  {
    id: '12',
    name: 'UP Scholarship for OBC Students',
    provider: 'UP Government',
    deadline: '12 September 2025',
    amount: '₹15,000/year',
    link: 'https://scholarship.up.gov.in',
    eligibility: {
      minAge: 17,
      maxAge: 28,
      course: ['B.Sc', 'M.Sc'],
      caste: ['OBC'],
      maxIncome: 200000,
      state: ['Uttar Pradesh'],
    },
  },
  {
    id: '13',
    name: 'Tamil Nadu Free Education Scheme',
    provider: 'Tamil Nadu Government',
    deadline: '1 September 2025',
    amount: 'Full Tuition Waiver',
    link: 'https://www.tn.gov.in/scholarships',
    eligibility: {
      minAge: 17,
      maxAge: 22,
      course: ['B.Com', 'BBA'],
      caste: ['SC', 'ST'],
      maxIncome: 250000,
      state: ['Tamil Nadu'],
    },
  },
  {
    id: '14',
    name: 'Delhi Merit Scholarship',
    provider: 'Delhi Directorate of Education',
    deadline: '30 August 2025',
    amount: '₹10,000/year',
    link: 'https://edistrict.delhigovt.nic.in',
    eligibility: {
      minAge: 16,
      maxAge: 25,
      course: ['B.Com', 'B.Sc'],
      caste: ['General', 'OBC'],
      maxIncome: 300000,
      state: ['Delhi'],
    },
  },
  {
    id: '15',
    name: 'West Bengal Talent Support Stipend',
    provider: 'West Bengal Government',
    deadline: '15 October 2025',
    amount: '₹12,000/year',
    link: 'https://wbmdfcscholarship.org',
    eligibility: {
      minAge: 17,
      maxAge: 26,
      course: ['B.Sc', 'B.A.', 'B.Com'],
      caste: ['All'],
      maxIncome: 200000,
      state: ['West Bengal'],
    },
  },
  {
  id: '16',
  name: 'INSPIRE Scholarship for Higher Education',
  provider: 'Department of Science and Technology',
  deadline: '15 October 2025',
  amount: '₹80,000/year',
  link: 'https://online-inspire.gov.in/',
  eligibility: {
    minAge: 17,
    maxAge: 22,
    course: ['B.Sc', 'B.Sc(Hons)', 'Integrated M.Sc'],
    caste: ['All'],
    maxIncome: 800000,
    state: ['All']
  }
},
{
  id: '17',
  name: 'AICTE Pragati Scholarship for Girls',
  provider: 'AICTE',
  deadline: '20 September 2025',
  amount: '₹50,000/year',
  link: 'https://aicte-india.org/',
  eligibility: {
    minAge: 17,
    maxAge: 25,
    course: ['B.Tech', 'Diploma'],
    caste: ['All'],
    maxIncome: 800000,
    state: ['All']
  }
},
{
  id: '18',
  name: 'PG Indira Gandhi Scholarship for Single Girl Child',
  provider: 'UGC',
  deadline: '10 December 2025',
  amount: '₹36,200/year',
  link: 'https://www.ugc.ac.in/',
  eligibility: {
    minAge: 20,
    maxAge: 30,
    course: ['PG'],
    caste: ['All'],
    maxIncome: 600000,
    state: ['All']
  }
},
{
  id: '19',
  name: 'E-Kalyan Scholarship for SC/ST/OBC (Jharkhand)',
  provider: 'Govt. of Jharkhand',
  deadline: '31 October 2025',
  amount: '₹25,000/year',
  link: 'https://ekalyan.cgg.gov.in/',
  eligibility: {
    minAge: 17,
    maxAge: 30,
    course: ['B.Tech', 'BA', 'BSc', 'MA', 'MSc'],
    caste: ['SC', 'ST', 'OBC'],
    maxIncome: 250000,
    state: ['Jharkhand']
  }
},
{
  id: '20',
  name: 'Maharashtra Post-Matric Scholarship',
  provider: 'Social Justice Dept., Maharashtra',
  deadline: '30 November 2025',
  amount: '₹12,000/year',
  link: 'https://mahadbt.maharashtra.gov.in/',
  eligibility: {
    minAge: 18,
    maxAge: 28,
    course: ['BA', 'B.Com', 'B.Sc', 'Diploma'],
    caste: ['SC', 'ST', 'OBC'],
    maxIncome: 250000,
    state: ['Maharashtra']
  }
},
{
  id: '21',
  name: 'Karnataka SSP Scholarship',
  provider: 'State Government of Karnataka',
  deadline: '15 September 2025',
  amount: '₹10,000/year',
  link: 'https://ssp.postmatric.karnataka.gov.in/',
  eligibility: {
    minAge: 17,
    maxAge: 25,
    course: ['Diploma', 'B.Tech'],
    caste: ['SC', 'ST', 'OBC'],
    maxIncome: 200000,
    state: ['Karnataka']
  }
},
{
  id: '22',
  name: 'Tata Trusts Means Grant for College Students',
  provider: 'Tata Trusts',
  deadline: '10 October 2025',
  amount: '₹20,000/year',
  link: 'https://www.tatatrusts.org/',
  eligibility: {
    minAge: 18,
    maxAge: 26,
    course: ['B.Com', 'BA', 'B.Sc'],
    caste: ['All'],
    maxIncome: 500000,
    state: ['All']
  }
},
{
  id: '23',
  name: 'Foundation for Excellence (FFE) Scholarship',
  provider: 'FFE India Trust',
  deadline: '1 August 2025',
  amount: '₹40,000/year',
  link: 'https://ffe.org/',
  eligibility: {
    minAge: 17,
    maxAge: 24,
    course: ['Engineering', 'MBBS'],
    caste: ['All'],
    maxIncome: 300000,
    state: ['All']
  }
},
{
  id: '24',
  name: 'Scholarship for Minority Students (NSP)',
  provider: 'Ministry of Minority Affairs',
  deadline: '15 October 2025',
  amount: '₹20,000/year',
  link: 'https://scholarships.gov.in/',
  eligibility: {
    minAge: 17,
    maxAge: 28,
    course: ['Any'],
    caste: ['All'],
    maxIncome: 250000,
    state: ['All']
  }
},
{
  id: '25',
  name: 'Nabanna Scholarship (West Bengal)',
  provider: 'West Bengal Government',
  deadline: '30 September 2025',
  amount: '₹10,000/year',
  link: 'https://wbcmo.gov.in/',
  eligibility: {
    minAge: 17,
    maxAge: 25,
    course: ['Any'],
    caste: ['All'],
    maxIncome: 60000,
    state: ['West Bengal']
  }
},
{
  id: '26',
  name: 'ONGC Scholarship for SC/ST Students',
  provider: 'ONGC Foundation',
  deadline: '1 November 2025',
  amount: '₹48,000/year',
  link: 'https://www.ongcscholar.org/',
  eligibility: {
    minAge: 17,
    maxAge: 30,
    course: ['Engineering', 'MBBS', 'MBA'],
    caste: ['SC', 'ST'],
    maxIncome: 200000,
    state: ['All']
  }
},
{
  id: '27',
  name: 'Santoor Women’s Scholarship',
  provider: 'Wipro Foundation',
  deadline: '25 August 2025',
  amount: '₹24,000/year',
  link: 'https://www.santoorscholarship.com/',
  eligibility: {
    minAge: 17,
    maxAge: 23,
    course: ['BA', 'BSc'],
    caste: ['All'],
    maxIncome: 200000,
    state: ['Karnataka', 'Andhra Pradesh', 'Telangana']
  }
},
{
  id: '28',
  name: 'Ishan Uday Scholarship for North Eastern Region',
  provider: 'UGC',
  deadline: '15 October 2025',
  amount: '₹7,800/month',
  link: 'https://www.ugc.ac.in/ner/',
  eligibility: {
    minAge: 18,
    maxAge: 25,
    course: ['Any UG'],
    caste: ['All'],
    maxIncome: 450000,
    state: ['Assam', 'Meghalaya', 'Manipur', 'Nagaland', 'Mizoram', 'Tripura', 'Sikkim', 'Arunachal Pradesh']
  }
},
{
  id: '29',
  name: 'Siemens Scholarship Program',
  provider: 'Siemens India',
  deadline: '30 August 2025',
  amount: '₹50,000/year + mentoring',
  link: 'https://www.siemens.co.in/',
  eligibility: {
    minAge: 18,
    maxAge: 22,
    course: ['B.Tech'],
    caste: ['All'],
    maxIncome: 200000,
    state: ['All']
  }
},
{
  id: '30',
  name: 'NSDL Shiksha Sahyog Scholarship',
  provider: 'NSDL e-Gov',
  deadline: '31 August 2025',
  amount: '₹12,000/year',
  link: 'https://www.vidyasaarathi.co.in/',
  eligibility: {
    minAge: 17,
    maxAge: 25,
    course: ['B.Com', 'BBA', 'BA'],
    caste: ['All'],
    maxIncome: 300000,
    state: ['All']
  }
}
];


export const RECOMMENDED_SCHEMES: Scheme[] = [
  {
    id: '1',
    title: 'National Scholarship for Students',
    department: 'Ministry of Education',
    description: 'Scholarship for meritorious students across India.',
    eligibility: 'Students scoring above 80% in Class 12',
    link: 'https://scholarships.gov.in',
    category: 'Student',
    tags: ['student', 'urgent'],
  },
  {
    id: '2',
    title: 'PM Kisan Scheme',
    department: 'Ministry of Agriculture',
    description: 'Direct income support for farmers.',
    eligibility: 'Small and marginal farmers',
    link: 'https://pmkisan.gov.in',
    category: 'Farmer',
    tags: ['farmer'],
  },
  {
    id: '3',
    title: 'Mahila Samman Yojana',
    department: 'Women & Child Development',
    description: 'Support scheme for women entrepreneurs.',
    eligibility: 'Women aged 18-40 with a business idea',
    link: 'https://wcd.nic.in',
    category: 'Women',
    tags: ['women'],
  },

  // === All 30 Scholarships Added Below ===

  {
    id: '4',
    title: 'Central Sector Scholarship',
    department: 'Department of Higher Education',
    description: '₹10,000 - ₹20,000 per annum for meritorious college students.',
    eligibility: 'Family income < ₹8L, age 17-22',
    link: 'https://scholarships.gov.in/',
    category: 'Scholarship',
    tags: ['college', 'merit'],
  },
  {
    id: '5',
    title: 'AICTE Pragati Scholarship for Girls',
    department: 'AICTE',
    description: '₹50,000 per annum for girl students in technical courses.',
    eligibility: 'Girls enrolled in B.Tech/B.E., income < ₹8L',
    link: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
    category: 'Scholarship',
    tags: ['girls', 'engineering'],
  },
  {
    id: '6',
    title: 'PM YASASVI Scheme',
    department: 'Ministry of Social Justice & Empowerment',
    description: 'Up to ₹1.25 lakh for OBC, EBC, and DNT students.',
    eligibility: 'OBC/EBC/DNT, income < ₹2.5L',
    link: 'https://yet.nta.ac.in/',
    category: 'Scholarship',
    tags: ['obc', 'minority'],
  },
  {
    id: '7',
    title: 'UP Post Matric Scholarship',
    department: 'Government of Uttar Pradesh',
    description: 'Financial aid for UP students in higher education.',
    eligibility: 'Residents of UP, income < ₹2L',
    link: 'https://scholarship.up.gov.in/',
    category: 'Scholarship',
    tags: ['state', 'up'],
  },
  {
    id: '8',
    title: 'NTSE Scholarship',
    department: 'NCERT',
    description: '₹1,250 - ₹2,000 per month for Class 10 students.',
    eligibility: 'Class 10 students qualifying NTSE exam',
    link: 'https://ncert.nic.in',
    category: 'Scholarship',
    tags: ['school', 'merit'],
  },
  {
    id: '9',
    title: 'INSPIRE Scholarship',
    department: 'DST',
    description: '₹80,000 per annum for science students.',
    eligibility: 'B.Sc./M.Sc. students, income < ₹8L',
    link: 'https://online-inspire.gov.in/',
    category: 'Scholarship',
    tags: ['science'],
  },
  {
    id: '10',
    title: 'KVPY Scholarship',
    department: 'DST',
    description: '₹5,000 - ₹7,000 per month for science streams.',
    eligibility: 'B.Sc./B.Stat students qualifying KVPY',
    link: 'http://kvpy.iisc.ernet.in/',
    category: 'Scholarship',
    tags: ['research'],
  },
  {
    id: '11',
    title: 'Saksham Scholarship',
    department: 'AICTE',
    description: '₹50,000 per year for differently-abled engineering students.',
    eligibility: 'Disability + B.Tech enrollment',
    link: 'https://aicte-india.org/schemes/students-development-schemes/Saksham',
    category: 'Scholarship',
    tags: ['disability'],
  },
  {
    id: '12',
    title: 'National Fellowship for OBC',
    department: 'UGC',
    description: '₹25,000 monthly fellowship for OBC students.',
    eligibility: 'OBC category postgraduates',
    link: 'https://ugc.ac.in',
    category: 'Scholarship',
    tags: ['obc'],
  },
  {
    id: '13',
    title: 'Maulana Azad Fellowship',
    department: 'Ministry of Minority Affairs',
    description: '₹28,000 per month for minority students.',
    eligibility: 'Muslim/Christian/Sikh/Buddhist/Parsi students',
    link: 'https://minorityaffairs.gov.in',
    category: 'Scholarship',
    tags: ['minority'],
  },
  {
    id: '14',
    title: 'Begum Hazrat Mahal Scholarship',
    department: 'MAEF',
    description: 'Up to ₹12,000 for female minority students.',
    eligibility: 'Female + minority category',
    link: 'https://maef.nic.in',
    category: 'Scholarship',
    tags: ['female'],
  },
  {
    id: '15',
    title: 'National Means-cum-Merit Scholarship',
    department: 'MHRD',
    description: '₹12,000 per year for Class 8 students.',
    eligibility: 'Income < ₹1.5L + Class 8',
    link: 'https://scholarships.gov.in',
    category: 'Scholarship',
    tags: ['school'],
  },
  {
    id: '16',
    title: 'ISHAN UDAY Scholarship',
    department: 'UGC',
    description: '₹5,400–₹7,800 monthly for NE students.',
    eligibility: 'Resident of North Eastern Region',
    link: 'https://ugc.ac.in',
    category: 'Scholarship',
    tags: ['northeast'],
  },
  {
    id: '17',
    title: 'PMRF',
    department: 'Ministry of Education',
    description: '₹70,000 monthly for PhD students.',
    eligibility: 'PhD in top institutes',
    link: 'https://pmrf.in',
    category: 'Scholarship',
    tags: ['phd'],
  },
  {
    id: '18',
    title: 'AIIMS Fellowship',
    department: 'AIIMS',
    description: '₹25,000 monthly for MD/MS students.',
    eligibility: 'Medical postgraduates',
    link: 'https://aiimsexams.ac.in',
    category: 'Scholarship',
    tags: ['medical'],
  },
  {
    id: '19',
    title: 'CSIR NET JRF',
    department: 'CSIR',
    description: '₹31,000/month fellowship for science postgrads.',
    eligibility: 'M.Sc. + NET qualified',
    link: 'https://csirnet.nta.ac.in',
    category: 'Scholarship',
    tags: ['jrf'],
  },
  {
    id: '20',
    title: 'UGC NET JRF',
    department: 'UGC',
    description: '₹31,000/month fellowship for postgrads.',
    eligibility: 'MA/M.Com/M.Sc. + NET',
    link: 'https://ugcnet.nta.nic.in',
    category: 'Scholarship',
    tags: ['ugc'],
  },
  {
    id: '21',
    title: 'LIC Golden Jubilee Scholarship',
    department: 'LIC',
    description: '₹10,000 annually for low-income families.',
    eligibility: 'Income < ₹2L',
    link: 'https://licindia.in',
    category: 'Scholarship',
    tags: ['lic'],
  },
  {
    id: '22',
    title: 'Siemens Scholarship',
    department: 'Siemens India',
    description: '₹75,000 per year for B.E./B.Tech students.',
    eligibility: 'Meritorious engineering students',
    link: 'https://www.siemens.co.in',
    category: 'Scholarship',
    tags: ['engineering'],
  },
  {
    id: '23',
    title: 'FFE India Scholarship',
    department: 'FFE',
    description: 'Tuition + living cost for needy students.',
    eligibility: 'B.Tech/MBBS students',
    link: 'https://ffe.org',
    category: 'Scholarship',
    tags: ['tech', 'mbbs'],
  },
  {
    id: '24',
    title: 'GATE Scholarship',
    department: 'MHRD',
    description: '₹12,400 per month for M.Tech students.',
    eligibility: 'Valid GATE score',
    link: 'https://education.gov.in',
    category: 'Scholarship',
    tags: ['gate'],
  },
  {
    id: '25',
    title: 'Nikon Scholarship',
    department: 'Nikon India',
    description: '₹1L for photography/design courses.',
    eligibility: 'Creative field students',
    link: 'https://buddy4study.com',
    category: 'Scholarship',
    tags: ['design'],
  },
  {
    id: '26',
    title: 'HDFC Parivartan ECS Scholarship',
    department: 'HDFC Bank',
    description: '₹15k to ₹75k for underprivileged students.',
    eligibility: 'Income < ₹3L',
    link: 'https://buddy4study.com',
    category: 'Scholarship',
    tags: ['hdfc'],
  },
  {
    id: '27',
    title: 'ONGC Scholarship for Meritorious Students',
    department: 'ONGC',
    description: '₹48,000 annually for selected courses.',
    eligibility: 'Engineering/MBBS/MBA/Geology',
    link: 'https://www.ongcscholar.org',
    category: 'Scholarship',
    tags: ['merit'],
  },
  {
    id: '28',
    title: 'Aditya Birla Scholarship',
    department: 'Aditya Birla Group',
    description: '₹1.8L per annum for MBA/Law students.',
    eligibility: 'Select institutes',
    link: 'https://www.adityabirlascholars.net',
    category: 'Scholarship',
    tags: ['mba', 'law'],
  },
  {
    id: '29',
    title: 'Sitaram Jindal Scholarship',
    department: 'SJF',
    description: '₹500–₹3,200 monthly for low-income students.',
    eligibility: 'Income < ₹4L',
    link: 'http://www.sitaramjindalfoundation.org',
    category: 'Scholarship',
    tags: ['jindal'],
  },
  {
    id: '30',
    title: 'Sashakt Scholarship',
    department: 'Dr. Reddy’s Foundation',
    description: '₹2.4L for 3 years for B.Sc. girls.',
    eligibility: 'B.Sc. + Female',
    link: 'https://www.sashaktscholarship.org',
    category: 'Scholarship',
    tags: ['female', 'science'],
  },
  {
    id: '31',
    title: 'ONGC SC/ST Scholarship',
    department: 'ONGC',
    description: '₹48,000 per annum for SC/ST students.',
    eligibility: 'SC/ST category',
    link: 'https://www.ongcscholar.org',
    category: 'Scholarship',
    tags: ['sc', 'st'],
  },
  {
    id: '32',
    title: 'Tata Trusts Scholarship',
    department: 'Tata Trusts',
    description: 'Scholarships for various courses.',
    eligibility: 'As per course',
    link: 'https://www.tatatrusts.org',
    category: 'Scholarship',
    tags: ['trust'],
  },
  {
    id: '33',
    title: 'Fair and Lovely Foundation Scholarship',
    department: 'Fair and Lovely Foundation',
    description: '₹25k–₹1L for girls from low-income families.',
    eligibility: 'Female, income < ₹3L',
    link: 'https://www.fairandlovelyfoundation.in',
    category: 'Scholarship',
    tags: ['female'],
  },
];


export const LEADERBOARD_DATA: LeaderboardUser[] = [
  { rank: 1, name: 'Ramesh Kumar', location: 'Punjab', tokens: 250, avatarUrl: 'https://i.pravatar.cc/150?img=1' },
  { rank: 2, name: 'Sunita Devi', location: 'Uttar Pradesh', tokens: 235, avatarUrl: 'https://i.pravatar.cc/150?img=5' },
  { rank: 3, name: 'Arjun Singh', location: 'Rajasthan', tokens: 210, avatarUrl: 'https://i.pravatar.cc/150?img=3' },
  { rank: 4, name: 'Ramesh Sharma', location: 'Maharashtra', tokens: 198, avatarUrl: 'https://i.pravatar.cc/150?img=8' },
  { rank: 5, name: 'Amit Patel', location: 'Gujarat', tokens: 180, avatarUrl: 'https://i.pravatar.cc/150?img=7' },
  { rank: 6, name: 'Vaibhav Reddy', location: 'Andhra Pradesh', tokens: 172, avatarUrl: 'https://i.pravatar.cc/150?img=11' },
  { rank: 7, name: 'Sandeep Tiwari', location: 'Madhya Pradesh', tokens: 165, avatarUrl: 'https://i.pravatar.cc/150?img=12' },
  { rank: 8, name: 'Arjun Das', location: 'West Bengal', tokens: 150, avatarUrl: 'https://i.pravatar.cc/150?img=14' },
];

// constants.ts
export type Perk = {
  id: string;
  title: string;
  description: string;
  icon: string;
  price: number;
  category: 'Premium' | 'Mentorship' | 'Exam' | 'Daily' | 'Mystery';
};

export const REDEEM_PERKS: Perk[] = [
  // Premium (2)
  { id:'premium-1', title:'Premium Scheme Access', description:'Unlock detailed guides and eligibility calculators.', icon:'🏆', price:60, category:'Premium' },
  { id:'premium-2', title:'Exclusive Webinar Access', description:'Attend govt strategy sessions.', icon:'🎤', price:50, category:'Premium' },
  // Mentorship (3)
  { id:'mentorship-1', title:'1-on-1 Mentor Call', description:'Talk to a scheme advisor.', icon:'📞', price:40, category:'Mentorship' },
  { id:'mentorship-2', title:'Resume Review Session', description:'Get your resume reviewed.', icon:'📝', price:30, category:'Mentorship' },
  { id:'mentorship-3', title:'Mock Interview (Govt Jobs)', description:'Simulated interview session.', icon:'🎯', price:35, category:'Mentorship' },
  // Exam (3)
  { id:'exam-1', title:'Exam Prep Kit', description:'Practice material for exams.', icon:'📚', price:25, category:'Exam' },
  { id:'exam-2', title:'Current Affairs Digest', description:'Monthly exam-focused PDF.', icon:'📰', price:15, category:'Exam' },
  { id:'exam-3', title:'Solved PYQ Papers', description:'Papers with solutions.', icon:'📄', price:20, category:'Exam' },
  // Daily (3)
  { id:'daily-1', title:'Daily Scheme Tip', description:'Daily scheme notifications.', icon:'📅', price:5, category:'Daily' },
  { id:'daily-2', title:'Token Booster – Ad Watch', description:'Earn 10 tokens by watching a video.', icon:'🎥', price:0, category:'Daily' },
  { id:'bonus-2', title:'Badge of Supporter', description:'Earn a profile badge.', icon:'🏅', price:5, category:'Daily' },
  // Mystery (2)
  { id:'mystery-1', title:'🎁 Mystery Box', description:'Get a surprise reward!', icon:'🎁', price:10, category:'Mystery' },
  { id:'mystery-2', title:'Secret Scheme Reveal', description:'Unlock hidden schemes.', icon:'🔍', price:15, category:'Mystery' },
];